# -*- coding: utf-8 -*-
##############################################################################
#
#    OpenERP, Open Source Management Solution
#    Copyright (C) 2004-2010 Tiny SPRL (<http://tiny.be>).
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
##############################################################################
# Generated by the OpenERP plugin for Dia !
{
        "name" : "rbienespu",
        "version" : "0.1",
        "author" : "Beatriz Coronel",
        "website" : "",
        "category" : "Bienes Publicos",
        "description": "Registro de Bienes""  """,
        "depends" : ['base','jasper_reports'],
        'data':     [
                        'report.xml',
                        'wizard/report_wizard_view.xml'
                    ],
        "init_xml" : [],
        #"init_xml" : ['data/estados.xml','data/municipios.xml','data/parroquias.xml','data/catalogo_general.xml','data/catalogo_subgeneral.xml','data/catalogo_esp.xml','data/estatus_bien.csv','data/estatus_uso.csv','data/forma_adquisicion.csv','data/seguros.csv','data/cobertura.csv','data/colores.csv','data/grupo.xml','data/clasificador_bien.xml','data/modelo.xml','data/detalle_modelo.xml','data/clase_sudebi.xml'],
       "demo_xml" : [ ],
        #"update_xml" : ['rbienespu_view.xml', 'security/ir.model.access.csv','data/estados.xml','data/municipios.xml','data/parroquias.xml','data/catalogo_general.xml','data/catalogo_subgeneral.xml','data/catalogo_esp.xml','data/grupo.xml','data/clasificador_bien.xml','data/modelo.xml','data/detalle_modelo.xml','data/marcas.xml','data/modelo_fab.xml','data/estatus_bien.xml','data/estatus_uso.xml','data/color_sudebi.xml','data/aseguradoras.xml','data/coberturas.xml','data/forma_adquisicion.xml','data/material.xml','data/uniadm_sudebi.xml','data/color.xml','data/clase_sudebi.xml'],
        "update_xml" : ['rbienespu_view.xml', 'security/ir.model.access.csv'],
        "installable": True
}
